import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                  >
           {/* add relative positioning to the main conent */}
           <div className="relative h-fit w-full z-10  whitespace-pre">

        {children}

           </div>

           {/* Sticky footer. The only important thing here is the z-index, the sticky position and the bottom value */}
           <div className="sticky z-0 bottom-0 left-0 w-full h-80 bg-primary/60 flex justify-center items-center">
             <div className="relative overflow-hidden w-full h-full flex justify-end px-12 text-right items-start py-12 text-primaryRed">
               <div className="flex flex-row space-x-12 sm:pace-x-16  md:space-x-24 text-sm sm:text-lg md:text-xl">
                 <ul>
                   <li className="hover:underline cursor-pointer">Home</li>
                   <li className="hover:underline cursor-pointer">Docs</li>
                   <li className="hover:underline cursor-pointer">Comps</li>
                 </ul>
                 <ul>
                   <li className="hover:underline cursor-pointer">Github</li>
                   <li className="hover:underline cursor-pointer">Instagram</li>
                   <li className="hover:underline cursor-pointer">X (Twitter)</li>
                 </ul>
               </div>
               <h2 className="absolute bottom-0 left-0  translate-y-1/3 sm:text-[192px]  text-[80px] text-primaryRed font-calendas">
                 fancy
               </h2>
             </div>
           </div>

                  </ThemeProvider>
      </body>
    </html>
  );
}
